FROM quay.io/fedora/fedora-bootc:44

RUN sed -i 's/^PRETTY_NAME=.*/PRETTY_NAME="Tetra"/; s/^NAME=.*/NAME="Tetra"/' /usr/lib/os-release

RUN dnf install -y \
    anaconda \
    anaconda-install-env-deps \
    anaconda-install-img-deps \
    anaconda-dracut \
    dracut-config-generic \
    dracut-network \
    net-tools \
    squashfs-tools \
    grub2-efi-x64-cdboot \
    python3-mako \
    lorax-templates-* \
    biosdevname \
    prefixdevname \
    && dnf clean all

# Fedora 44 bootc requires manual EFI vendor setup for ISO generation
RUN mkdir -p /boot/efi && cp -ra /usr/lib/efi/*/*/EFI /boot/efi

# lorax workaround -- /var/mnt may not exist on bootc images
RUN mkdir -p /var/mnt
