FROM quay.io/fedora/fedora-bootc:43

# ==============================================================================
# Base Image & Core Packages
# ==============================================================================
# Base server image
# Enable LTS kernel COPR
COPY assets/kwizart-kernel-longterm.repo /etc/yum.repos.d/kwizart-kernel-longterm.repo

# ==============================================================================
# Package Modifications
# ==============================================================================
# Disable systemd-remount-fs.service to prevent failure on read-only bootc systems
RUN systemctl mask systemd-remount-fs.service

# Remove Plymouth completely
RUN dnf remove -y plymouth

# Configure repos, swap to LTS kernel, install tools, configure Docker, and configure fastfetch
RUN dnf install -y https://zfsonlinux.org/fedora/zfs-release-3-0$(rpm -E %dist).noarch.rpm && \
    dnf swap -y kernel-core kernel-longterm-core --allowerasing && \
    dnf install -y kernel-longterm kernel-longterm-devel \
    kernel-longterm-modules kernel-longterm-modules-extra \
    zfs screen fastfetch git && \
    dnf config-manager addrepo --from-repofile https://download.docker.com/linux/fedora/docker-ce.repo && \
    dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin && \
    systemctl enable docker && \
    git clone https://github.com/OptimoSupreme/fastfetch_config /etc/skel/.config/fastfetch

# ==============================================================================
# System Configuration
# ==============================================================================
# Rename OS in GRUB and Fastfetch
RUN sed -i 's/^PRETTY_NAME=.*/PRETTY_NAME="Tetra"/; s/^NAME=.*/NAME="Tetra"/' /usr/lib/os-release
# Set Hostname
RUN echo "morgoth" > /etc/hostname

# ==============================================================================
# Housekeeping
# ==============================================================================
RUN dnf autoremove -y && \
    dnf clean all
