FROM quay.io/fedora/fedora-bootc:43

# ==============================================================================
# Base Image & Core Packages
# ==============================================================================
# Base server image
# Enable LTS kernel COPR
COPY assets/kwizart-kernel-longterm.repo /etc/yum.repos.d/kwizart-kernel-longterm.repo

# ==============================================================================
# Package Modifications
# ==============================================================================
# Disable systemd-remount-fs.service to prevent failure on read-only bootc systems
RUN systemctl mask systemd-remount-fs.service

# Remove Packages from base image
RUN dnf remove -y plymouth

# Configure repos and install packages
RUN dnf install -y https://zfsonlinux.org/fedora/zfs-release-3-0$(rpm -E %dist).noarch.rpm && \
    dnf swap -y kernel-core kernel-longterm-core --allowerasing && \
    dnf install -y kernel-longterm kernel-longterm-devel \
    kernel-longterm-modules kernel-longterm-modules-extra \
    zfs screen fastfetch git chafa ImageMagick && \
    dnf config-manager addrepo --from-repofile https://download.docker.com/linux/fedora/docker-ce.repo && \
    dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin && \
    systemctl enable docker && \
    git clone https://github.com/OptimoSupreme/fastfetch_config /etc/skel/.config/fastfetch

# ==============================================================================
# System Configuration
# ==============================================================================
# Name OS in GRUB and Fastfetch
RUN sed -i 's/^PRETTY_NAME=.*/PRETTY_NAME="Tetra"/; s/^NAME=.*/NAME="Tetra"/' /usr/lib/os-release
# Set Timezone and Enable Internet Time
RUN ln -fs ../usr/share/zoneinfo/US/Eastern /etc/localtime && \
    systemctl enable chronyd

# Set Hostname
RUN echo "morgoth" > /etc/hostname && \
    echo "f+ /etc/hostname 0644 root root - morgoth" > /usr/lib/tmpfiles.d/10-set-hostname.conf

# ==============================================================================
# Housekeeping
# ==============================================================================
RUN dnf autoremove -y && \
    dnf clean all
