FROM quay.io/fedora/fedora-bootc:latest

# Base workstation image
# Install fastfetch, config, GNOME Desktop, and cursor theme
RUN dnf install -y fastfetch git breeze-cursor-theme \
    @workstation-product-environment && \
    dnf clean all && \
    git clone https://github.com/OptimoSupreme/fastfetch_config /etc/skel/.config/fastfetch && \
    systemctl enable gdm.service

# Apply global GNOME dconf settings (cursor, fonts, window buttons)
COPY config/dconf-profile /etc/dconf/profile/user
COPY config/dconf-settings /etc/dconf/db/local.d/00-custom
RUN dconf update

# Add configurations and packages for personal computers here
