FROM quay.io/fedora/fedora-coreos:stable

# Base server image
# Install fastfetch and specific user config
RUN rpm-ostree install -y fastfetch git && \
    ostree container commit && \
    git clone https://github.com/OptimoSupreme/fastfetch_config /etc/skel/.config/fastfetch

# Add configurations and packages for the server here
