FROM quay.io/fedora/fedora-bootc:latest

# Base generic desktop image
# Install fastfetch, config, GNOME Desktop, and cursor theme
RUN dnf install -y fastfetch git breeze-cursor-theme \
    @workstation-product-environment && \
    dnf remove -y gnome-contacts gnome-weather gnome-clocks mediawriter gnome-maps 'libreoffice*' gnome-boxes gnome-connections snapshot gnome-characters gnome-font-viewer gnome-logs malcontent gnome-tour yelp && \
    dnf clean all && \
    git clone https://github.com/OptimoSupreme/fastfetch_config /etc/skel/.config/fastfetch && \
    systemctl enable gdm.service

# Apply global GNOME dconf settings and wallpaper
RUN rm -rf /usr/share/backgrounds/*
COPY global_assets/wallpaper.jpg /usr/share/backgrounds/default.jpg
COPY global_assets/dconf-profile /etc/dconf/profile/user
COPY global_assets/dconf-settings /etc/dconf/db/local.d/00-custom
RUN dconf update

# Add user-friendly, non-technical configurations and packages here
