FROM quay.io/fedora/fedora-bootc:latest

# Install RPM Fusion and NVIDIA drivers
# Note: Building the akmod requires kernel-devel and compiling the module for the container's kernel
RUN dnf install -y \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
    dnf install -y akmod-nvidia xorg-x11-drv-nvidia-cuda && \
    akmods --force --kernels $(ls /lib/modules) && \
    dnf clean all

# Base generic desktop image with NVIDIA support
# Install fastfetch, config, GNOME Desktop, and cursor theme
RUN dnf install -y fastfetch git breeze-cursor-theme \
    @workstation-product-environment && \
    dnf remove -y gnome-contacts gnome-weather gnome-clocks mediawriter gnome-maps 'libreoffice*' gnome-boxes gnome-connections snapshot gnome-characters gnome-font-viewer gnome-logs malcontent gnome-tour yelp && \
    dnf clean all && \
    git clone https://github.com/OptimoSupreme/fastfetch_config /etc/skel/.config/fastfetch && \
    systemctl enable gdm.service

# Apply global GNOME dconf settings and wallpaper
RUN rm -rf /usr/share/backgrounds/*
COPY global_assets/wallpaper.jpg /usr/share/backgrounds/default.jpg
COPY global_assets/dconf-profile /etc/dconf/profile/user
COPY global_assets/dconf-settings /etc/dconf/db/local.d/00-custom
RUN dconf update

# Add user-friendly, non-technical configurations and packages here
