FROM quay.io/fedora/fedora-bootc:latest

# Base generic desktop image
# Install fastfetch, config, and GNOME Desktop
RUN dnf install -y fastfetch git \
    @workstation-product-environment && \
    dnf clean all && \
    git clone https://github.com/OptimoSupreme/fastfetch_config /etc/skel/.config/fastfetch && \
    systemctl enable gdm.service

# Add user-friendly, non-technical configurations and packages here
