[org/gnome/shell/extensions/dash-to-panel]
animate-appicon-hover-animation-extent={'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}
appicon-margin=3
appicon-style='NORMAL'
dot-position='TOP'
dot-style-focused='DOTS'
dot-style-unfocused='DOTS'
extension-version=72
focus-highlight-dominant=true
global-border-radius=0
group-apps=true
hide-overview-on-startup=true
highlight-appicon-hover=true
hotkeys-overlay-combo='TEMPORARILY'
intellihide=false
intellihide-hide-from-windows=true
isolate-monitors=true
isolate-workspaces=true
panel-anchors='{"VSC-WBJ211901576":"MIDDLE"}'
panel-element-positions='{"VSC-WBJ211901576":[{"element":"showAppsButton","visible":true,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"centerBox","visible":true,"position":"stackedBR"},{"element":"dateMenu","visible":true,"position":"centerMonitor"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":false,"position":"stackedBR"}]}'
panel-lengths='{"VSC-WBJ211901576":100}'
panel-positions='{"VSC-WBJ211901576":"TOP"}'
panel-side-margins=0
panel-sizes='{"VSC-WBJ211901576":34}'
panel-top-bottom-margins=0
panel-top-bottom-padding=0
prefs-opened=true
primary-monitor='VSC-WBJ211901576'
show-apps-icon-file=''
show-window-previews=false
stockgs-keep-dash=false
stockgs-keep-top-panel=false
trans-bg-color='#241f31'
trans-dynamic-anim-target=0.90000000000000002
trans-panel-opacity=0.70000000000000007
trans-use-border=false
trans-use-custom-bg=false
trans-use-custom-opacity=false
trans-use-dynamic-opacity=false
window-preview-title-position='TOP'
